-- AlterTable
ALTER TABLE "Comment" ADD COLUMN     "downCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "upCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "voteScore" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "downCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "upCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "voteScore" INTEGER NOT NULL DEFAULT 0;
